services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Nếu cần kết nối với các service khác, có thể dùng depends_on
    networks:
      - julynetwork
    volumes:
      - ./api:/app
      - /app/node_modules
      # - ./api/node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost
      - REACT_APP_BACKEND_PORT=3000

    networks:
      - julynetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # - ./frontend/node_modules:/app/node_modules
    depends_on:
      - api

networks:
  julynetwork:
    driver: bridge